// Command stabilitytool enumerates the public API that is exempt from the
// project's SemVer promise.
//
// The op package documents the convention that an API whose godoc starts with
// "Experimental:" may change without a major bump. That makes the set of
// marked symbols the exemption list, and everything else implicitly stable —
// so the exemption list is the thing worth pinning down before a major
// release. This command derives it from the source rather than asking anyone
// to maintain it by hand, and compares it against a checked-in report so a
// marker that appears, moves, or disappears shows up as a reviewable diff.
//
// Usage:
//
//	stabilitytool -root <dir> -module <path>            # print the report
//	stabilitytool -root <dir> -module <path> -write f   # regenerate f
//	stabilitytool -root <dir> -module <path> -check f   # fail on drift
package main

import (
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// experimentalMarker introduces the rationale for an exemption. The convention
// is documented in op/doc.go.
const experimentalMarker = "Experimental:"

// stableMarker is the counterpart form ("Stable since v0.9"). A symbol
// carrying both is contradictory and is reported as an error.
const stableMarker = "Stable since"

// entry is one exempt symbol.
type entry struct {
	ImportPath string
	Symbol     string
}

func main() {
	var (
		root     = flag.String("root", "op", "directory tree to scan, relative to the working directory")
		module   = flag.String("module", "", "module path that -root maps onto (required)")
		write    = flag.String("write", "", "regenerate the report at this path")
		checkArg = flag.String("check", "", "compare against the report at this path and exit non-zero on drift")
	)
	flag.Parse()

	if *module == "" {
		fail(errors.New("-module is required"))
	}

	entries, err := scan(*root, *module)
	if err != nil {
		fail(err)
	}
	report := render(entries)

	switch {
	case *write != "":
		if err := os.WriteFile(*write, []byte(report), 0o644); err != nil {
			fail(err)
		}
	case *checkArg != "":
		if err := check(*checkArg, report); err != nil {
			fail(err)
		}
	default:
		fmt.Print(report)
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "stabilitytool:", err)
	os.Exit(1)
}

// check compares the freshly derived report against the checked-in one and
// describes the drift in terms of symbols rather than diff hunks, so the
// failure names what to do about it.
func check(path, report string) error {
	recorded, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if string(recorded) == report {
		return nil
	}
	added, removed := diff(parseReport(string(recorded)), parseReport(report))
	var b strings.Builder
	fmt.Fprintf(&b, "%s is out of date\n", path)
	for _, s := range added {
		fmt.Fprintf(&b, "  + %s\n", s)
	}
	for _, s := range removed {
		fmt.Fprintf(&b, "  - %s\n", s)
	}
	b.WriteString("the experimental surface changed; run 'make stability' and " +
		"confirm the change belongs in the release notes")
	return errors.New(b.String())
}

// parseReport returns the symbol lines of a report, ignoring the comment
// header so the header can be reworded without looking like drift.
func parseReport(s string) []string {
	var out []string
	for _, line := range strings.Split(s, "\n") {
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, line)
	}
	return out
}

func diff(old, current []string) (added, removed []string) {
	inOld := make(map[string]bool, len(old))
	for _, s := range old {
		inOld[s] = true
	}
	inCurrent := make(map[string]bool, len(current))
	for _, s := range current {
		inCurrent[s] = true
	}
	for _, s := range current {
		if !inOld[s] {
			added = append(added, s)
		}
	}
	for _, s := range old {
		if !inCurrent[s] {
			removed = append(removed, s)
		}
	}
	return added, removed
}

func render(entries []entry) string {
	var b strings.Builder
	b.WriteString("# Public API exempt from the SemVer promise.\n")
	b.WriteString("# Every symbol here carries an \"Experimental:\" godoc marker and may\n")
	b.WriteString("# change in a minor release. Anything not listed is stable.\n")
	b.WriteString("# Generated by tools/stabilitytool; run 'make stability' to refresh.\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "%s\t%s\n", e.ImportPath, e.Symbol)
	}
	return b.String()
}

// scan walks root, parses every non-test Go file, and returns the exempt
// symbols sorted by import path then symbol.
func scan(root, module string) ([]entry, error) {
	var (
		entries []entry
		problem []string
	)
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		importPath, err := importPathFor(path, root, module)
		if err != nil {
			return err
		}
		found, issues, err := scanFile(path, importPath)
		if err != nil {
			return err
		}
		entries = append(entries, found...)
		problem = append(problem, issues...)
		return nil
	})
	if err != nil {
		return nil, err
	}
	if len(problem) > 0 {
		return nil, fmt.Errorf("malformed stability markers:\n  %s", strings.Join(problem, "\n  "))
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].ImportPath != entries[j].ImportPath {
			return entries[i].ImportPath < entries[j].ImportPath
		}
		return entries[i].Symbol < entries[j].Symbol
	})
	return entries, nil
}

// importPathFor maps a file path back onto the import path of its package.
func importPathFor(path, root, module string) (string, error) {
	dir := filepath.Dir(path)
	rel, err := filepath.Rel(root, dir)
	if err != nil {
		return "", err
	}
	if rel == "." {
		return module, nil
	}
	return module + "/" + filepath.ToSlash(rel), nil
}

func scanFile(path, importPath string) (entries []entry, issues []string, err error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, nil, err
	}
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.FuncDecl:
			name, ok := funcSymbol(d)
			if !ok {
				continue
			}
			e, issue := classify(importPath, name, d.Doc, fset, d.Pos())
			entries, issues = collect(entries, issues, e, issue)
		case *ast.GenDecl:
			entries, issues = scanGenDecl(d, importPath, fset, entries, issues)
		}
	}
	return entries, issues, nil
}

// scanGenDecl handles type, const, and var groups. A grouped declaration can
// carry the marker on the group or on an individual spec, and both forms
// appear in this repository, so each spec falls back to the group's doc.
func scanGenDecl(
	d *ast.GenDecl,
	importPath string,
	fset *token.FileSet,
	entries []entry,
	issues []string,
) ([]entry, []string) {
	for _, spec := range d.Specs {
		var (
			name string
			doc  = d.Doc
			pos  = d.Pos()
		)
		switch s := spec.(type) {
		case *ast.TypeSpec:
			name = s.Name.Name
			if s.Doc != nil {
				doc = s.Doc
			}
			pos = s.Pos()
		case *ast.ValueSpec:
			if len(s.Names) == 0 {
				continue
			}
			name = s.Names[0].Name
			if s.Doc != nil {
				doc = s.Doc
			}
			pos = s.Pos()
		default:
			continue
		}
		if !ast.IsExported(name) {
			continue
		}
		e, issue := classify(importPath, name, doc, fset, pos)
		entries, issues = collect(entries, issues, e, issue)
	}
	return entries, issues
}

func collect(entries []entry, issues []string, e *entry, issue string) ([]entry, []string) {
	if e != nil {
		entries = append(entries, *e)
	}
	if issue != "" {
		issues = append(issues, issue)
	}
	return entries, issues
}

// funcSymbol names a function or a method on an exported receiver. Methods on
// unexported receivers are not part of the public surface.
func funcSymbol(d *ast.FuncDecl) (string, bool) {
	if d.Recv == nil {
		return d.Name.Name, ast.IsExported(d.Name.Name)
	}
	if !ast.IsExported(d.Name.Name) || len(d.Recv.List) == 0 {
		return "", false
	}
	recv := receiverName(d.Recv.List[0].Type)
	if recv == "" || !ast.IsExported(recv) {
		return "", false
	}
	return recv + "." + d.Name.Name, true
}

func receiverName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return receiverName(t.X)
	case *ast.IndexExpr: // generic receiver, for example Foo[T]
		return receiverName(t.X)
	case *ast.IndexListExpr:
		return receiverName(t.X)
	}
	return ""
}

// classify decides whether a symbol is exempt and reports a malformed marker.
// A marker with no rationale is treated as an error because the whole point of
// the exemption is to tell an embedder what is expected to change.
func classify(
	importPath, name string,
	doc *ast.CommentGroup,
	fset *token.FileSet,
	pos token.Pos,
) (*entry, string) {
	if doc == nil {
		return nil, ""
	}
	text := doc.Text()
	idx := strings.Index(text, experimentalMarker)
	if idx < 0 {
		return nil, ""
	}
	where := fset.Position(pos)
	if strings.Contains(text, stableMarker) {
		return nil, fmt.Sprintf("%s:%d: %s carries both %q and %q",
			where.Filename, where.Line, name, experimentalMarker, stableMarker)
	}
	rationale := strings.TrimSpace(text[idx+len(experimentalMarker):])
	if rationale == "" {
		return nil, fmt.Sprintf("%s:%d: %s has %q with no rationale",
			where.Filename, where.Line, name, experimentalMarker)
	}
	return &entry{ImportPath: importPath, Symbol: name}, ""
}
