package clientauth

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"errors"
	"fmt"
	"math/big"
	"sync"

	"golang.org/x/crypto/argon2"

	"github.com/libraz/go-oidc-provider/internal/argon2id"
)

// SecretVerifier is the pluggable contract for verifying a presented
// client_secret against the stored hash. The library ships a built-in
// argon2id implementation ([Argon2id]) and embedders MAY register an
// alternative if their existing user database stores secrets under a
// different scheme.
type SecretVerifier interface {
	// Verify reports whether the presented plaintext secret matches the
	// stored hash. Implementations MUST run in constant time relative
	// to the secret length and MUST NOT log the plaintext value.
	Verify(presented, stored string) error
}

// Argon2id is the library's reference SecretVerifier. It accepts hashes
// in the format produced by [Argon2id.Hash], which mirrors the modular
// crypt format ($argon2id$...$salt$hash) so embedders can interoperate
// with other tools that read the same encoding.
//
// Parameters target OWASP's 2024 password-hashing guidance: m=64MB, t=3,
// p=1. Embedders MAY tune via [Argon2idParams] but the defaults are the
// ones the library tests against.
type Argon2id struct {
	Params Argon2idParams
}

// Argon2idParams configures the Argon2id reference verifier. Zero values
// fall back to the library defaults via [Argon2idDefaults].
type Argon2idParams struct {
	// Memory is the memory cost in KiB. OWASP recommends ≥ 19MiB; the
	// library default is 64MiB.
	Memory uint32
	// Iterations is the time cost. OWASP recommends ≥ 2; default 3.
	Iterations uint32
	// Parallelism is the lanes count. Library default 1.
	Parallelism uint8
	// SaltLength is the salt size in bytes generated by [Argon2id.Hash].
	// Library default 16.
	SaltLength uint32
	// KeyLength is the derived-key size in bytes generated by
	// [Argon2id.Hash]. Library default 32.
	KeyLength uint32
}

// Argon2idDefaults returns the parameters used when the caller leaves
// [Argon2idParams] zero-valued.
func Argon2idDefaults() Argon2idParams {
	return Argon2idParams{
		Memory:      64 * 1024,
		Iterations:  3,
		Parallelism: 1,
		SaltLength:  16,
		KeyLength:   32,
	}
}

// resolved returns a copy of p with zero-valued fields filled in from
// [Argon2idDefaults]. The returned value never contains zeros.
func (p Argon2idParams) resolved() Argon2idParams {
	d := Argon2idDefaults()
	if p.Memory == 0 {
		p.Memory = d.Memory
	}
	if p.Iterations == 0 {
		p.Iterations = d.Iterations
	}
	if p.Parallelism == 0 {
		p.Parallelism = d.Parallelism
	}
	if p.SaltLength == 0 {
		p.SaltLength = d.SaltLength
	}
	if p.KeyLength == 0 {
		p.KeyLength = d.KeyLength
	}
	return p
}

// Hash derives an Argon2id encoding of secret using the verifier's
// configured parameters. The salt is sourced from crypto/rand.
func (a *Argon2id) Hash(secret string) (string, error) {
	p := a.Params.resolved()
	if err := validateHashParams(p); err != nil {
		return "", err
	}
	salt := make([]byte, p.SaltLength)
	if _, err := rand.Read(salt); err != nil {
		return "", fmt.Errorf("authn: read salt: %w", err)
	}
	key := argon2.IDKey([]byte(secret), salt, p.Iterations, p.Memory, p.Parallelism, p.KeyLength)
	enc := fmt.Sprintf("$argon2id$v=%d$m=%d,t=%d,p=%d$%s$%s",
		argon2.Version,
		p.Memory, p.Iterations, p.Parallelism,
		base64.RawStdEncoding.EncodeToString(salt),
		base64.RawStdEncoding.EncodeToString(key),
	)
	return enc, nil
}

func validateHashParams(p Argon2idParams) error {
	policy := Argon2idPolicy()
	switch {
	case p.Memory < policy.MinMemory:
		return fmt.Errorf("%w: memory %d KiB below %d KiB", ErrInsecureParams, p.Memory, policy.MinMemory)
	case p.Iterations < policy.MinIterations:
		return fmt.Errorf("%w: iterations %d below %d", ErrInsecureParams, p.Iterations, policy.MinIterations)
	case p.Parallelism < policy.MinParallelism:
		return fmt.Errorf("%w: parallelism %d below %d", ErrInsecureParams, p.Parallelism, policy.MinParallelism)
	case int(p.SaltLength) < policy.MinSaltLength:
		return fmt.Errorf("%w: salt length %d below %d", ErrInsecureParams, p.SaltLength, policy.MinSaltLength)
	case int(p.KeyLength) < policy.MinKeyLength:
		return fmt.Errorf("%w: key length %d below %d", ErrInsecureParams, p.KeyLength, policy.MinKeyLength)
	default:
		return nil
	}
}

// Verify implements [SecretVerifier]. It rejects malformed encodings,
// version mismatches, and parameter values that violate
// [argon2id.DefaultPolicy] (which encodes the OWASP 2024 minima);
// otherwise it derives the candidate key and compares it in constant
// time. Every failure path collapses onto [ErrCredentialsInvalid] so
// an attacker probing with synthetic stored values cannot fingerprint
// the parser.
func (a *Argon2id) Verify(presented, stored string) error {
	switch err := argon2id.Verify([]byte(presented), stored, Argon2idPolicy()); {
	case err == nil:
		return nil
	case errors.Is(err, argon2id.ErrMismatch),
		errors.Is(err, argon2id.ErrEncoding),
		errors.Is(err, argon2id.ErrPolicy):
		return ErrCredentialsInvalid
	default:
		return ErrCredentialsInvalid
	}
}

// Argon2idMinMemory is the OWASP 2024 minimum memory cost for
// Argon2id, in KiB (19 MiB). The verifier rejects stored hashes whose
// "m=" parameter is below this floor so a database leak cannot be
// compounded by trivially-broken work factors.
const Argon2idMinMemory uint32 = 19 * 1024

// Argon2idMinIterations is the OWASP 2024 minimum iteration count
// (time cost) for Argon2id. The verifier rejects stored hashes whose
// "t=" parameter is below this floor.
const Argon2idMinIterations uint32 = 2

// Argon2idPolicy is the [argon2id.Policy] this verifier applies to
// stored client_secret hashes. The bounds inherit from
// [argon2id.DefaultPolicy] (OWASP 2024 minima + practical upper caps);
// embedders that interoperate with an external hash store can read the
// returned struct to align their migration tooling with the verifier's
// fence.
func Argon2idPolicy() argon2id.Policy {
	return argon2id.DefaultPolicy()
}

// ensure compile-time interface satisfaction.
var _ SecretVerifier = (*Argon2id)(nil)

// dummyVerify is a constant-time no-op used by [VerifyClient] when the
// caller targets a confidential method but the registered client has no
// stored hash. Without this the verifier would short-circuit before the
// hash work, leaking the existence of the client through timing.
//
// The function is unexported because it is only useful in conjunction
// with [VerifyClient].
func dummyVerify(presented string) {
	// Use the same Argon2id parameter set the verifier would use, so
	// the timing of the dummy path approximates the real one.
	p := Argon2idDefaults()
	_ = argon2.IDKey([]byte(presented), make([]byte, p.SaltLength),
		p.Iterations, p.Memory, p.Parallelism, p.KeyLength)
}

// dummyJWTVerify is the private_key_jwt counterpart to [dummyVerify].
// It runs a single ES256 signature verification against a fixed P-256
// public key so the "unknown client" branch of [VerifyClient] takes
// the same wall-clock budget as the verify branch that talks to a real
// AssertionVerifier. Without this the latency between "no such client"
// and "wrong signature" leaks client_id existence through timing alone
// even when [runDummyVerify] is engaged on the secret-method side.
//
// The function never produces a result and never returns an error;
// callers SHOULD invoke it for its side-effect on wall-clock cost
// only.
func dummyJWTVerify() {
	pub := dummyECDSAKey()
	// A deterministic message (zero-filled SHA-256 hash) and a
	// non-zero (r, s) pair guarantee the verify call exercises
	// the full P-256 ladder; the result is intentionally ignored.
	digest := sha256.Sum256(nil)
	_ = ecdsa.Verify(pub, digest[:], dummyECDSAR, dummyECDSAS)
}

// dummyECDSAKeyOnce / dummyECDSAKeyCache cache the public key the
// dummy verify uses. Generating a fresh key per call would dominate
// the dummy's wall-clock cost and violate the "fixed-cost" intent.
//
//nolint:gochecknoglobals // cache for the fixed-cost dummy key.
var (
	dummyECDSAKeyOnce  sync.Once
	dummyECDSAKeyCache *ecdsa.PublicKey
)

// dummyECDSAR / dummyECDSAS are the fixed (r, s) pair the dummy verify
// hands to ecdsa.Verify. Both are below the P-256 group order so the
// verify call walks the full constant-time ladder before reporting
// failure. The values are public, deterministic, and never used
// outside the timing shim.
//
//nolint:gochecknoglobals // immutable fixed-cost dummy signature.
var (
	dummyECDSAR = new(big.Int).SetBytes([]byte{
		0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
		0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10,
		0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18,
		0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f, 0x20,
	})
	dummyECDSAS = new(big.Int).SetBytes([]byte{
		0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, 0x28,
		0x29, 0x2a, 0x2b, 0x2c, 0x2d, 0x2e, 0x2f, 0x30,
		0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, 0x38,
		0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f, 0x40,
	})
)

// dummyECDSAKey returns the cached fixed P-256 public key the dummy
// verify hands to ecdsa.Verify. The key is generated once per process
// from crypto/rand; subsequent calls return the same value so the
// dummy work factor is stable across invocations.
func dummyECDSAKey() *ecdsa.PublicKey {
	dummyECDSAKeyOnce.Do(func() {
		priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
		if err != nil {
			// crypto/rand failure inside sync.Once is fatal: the
			// dummy verify is useless without a key, and we have
			// no error channel back to the caller. The same
			// failure would crash any subsequent secret-related
			// operation.
			//nolint:forbidigo // unrecoverable RNG failure inside sync.Once; library cannot proceed without entropy.
			panic(fmt.Errorf("authn: dummy P-256 keygen: %w", err))
		}
		dummyECDSAKeyCache = &priv.PublicKey
	})
	return dummyECDSAKeyCache
}
