package clientauth

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"fmt"
	"strconv"
	"strings"

	"golang.org/x/crypto/argon2"
)

// SecretVerifier is the pluggable contract for verifying a presented
// client_secret against the stored hash. The library ships a built-in
// argon2id implementation ([Argon2id]) and embedders MAY register an
// alternative if their existing user database stores secrets under a
// different scheme.
type SecretVerifier interface {
	// Verify reports whether the presented plaintext secret matches the
	// stored hash. Implementations MUST run in constant time relative
	// to the secret length and MUST NOT log the plaintext value.
	Verify(presented, stored string) error
}

// Argon2id is the library's reference SecretVerifier. It accepts hashes
// in the format produced by [Argon2id.Hash], which mirrors the modular
// crypt format ($argon2id$...$salt$hash) so embedders can interoperate
// with other tools that read the same encoding.
//
// Parameters target OWASP's 2024 password-hashing guidance: m=64MB, t=3,
// p=1. Embedders MAY tune via [Argon2idParams] but the defaults are the
// ones the library tests against.
type Argon2id struct {
	Params Argon2idParams
}

// Argon2idParams configures the Argon2id reference verifier. Zero values
// fall back to the library defaults via [Argon2idDefaults].
type Argon2idParams struct {
	// Memory is the memory cost in KiB. OWASP recommends ≥ 19MiB; the
	// library default is 64MiB.
	Memory uint32
	// Iterations is the time cost. OWASP recommends ≥ 2; default 3.
	Iterations uint32
	// Parallelism is the lanes count. Library default 1.
	Parallelism uint8
	// SaltLength is the salt size in bytes generated by [Argon2id.Hash].
	// Library default 16.
	SaltLength uint32
	// KeyLength is the derived-key size in bytes generated by
	// [Argon2id.Hash]. Library default 32.
	KeyLength uint32
}

// Argon2idDefaults returns the parameters used when the caller leaves
// [Argon2idParams] zero-valued.
func Argon2idDefaults() Argon2idParams {
	return Argon2idParams{
		Memory:      64 * 1024,
		Iterations:  3,
		Parallelism: 1,
		SaltLength:  16,
		KeyLength:   32,
	}
}

// resolved returns a copy of p with zero-valued fields filled in from
// [Argon2idDefaults]. The returned value never contains zeros.
func (p Argon2idParams) resolved() Argon2idParams {
	d := Argon2idDefaults()
	if p.Memory == 0 {
		p.Memory = d.Memory
	}
	if p.Iterations == 0 {
		p.Iterations = d.Iterations
	}
	if p.Parallelism == 0 {
		p.Parallelism = d.Parallelism
	}
	if p.SaltLength == 0 {
		p.SaltLength = d.SaltLength
	}
	if p.KeyLength == 0 {
		p.KeyLength = d.KeyLength
	}
	return p
}

// Hash derives an Argon2id encoding of secret using the verifier's
// configured parameters. The salt is sourced from crypto/rand.
func (a *Argon2id) Hash(secret string) (string, error) {
	p := a.Params.resolved()
	salt := make([]byte, p.SaltLength)
	if _, err := rand.Read(salt); err != nil {
		return "", fmt.Errorf("authn: read salt: %w", err)
	}
	key := argon2.IDKey([]byte(secret), salt, p.Iterations, p.Memory, p.Parallelism, p.KeyLength)
	enc := fmt.Sprintf("$argon2id$v=%d$m=%d,t=%d,p=%d$%s$%s",
		argon2.Version,
		p.Memory, p.Iterations, p.Parallelism,
		base64.RawStdEncoding.EncodeToString(salt),
		base64.RawStdEncoding.EncodeToString(key),
	)
	return enc, nil
}

// Verify implements [SecretVerifier]. It rejects malformed encodings,
// version mismatches, and parameter values that fall below the verifier's
// minima; otherwise it derives the candidate key and compares it in
// constant time.
func (a *Argon2id) Verify(presented, stored string) error {
	parsed, err := parseArgon2idEncoding(stored)
	if err != nil {
		return err
	}
	keyLen := len(parsed.hash)
	// argon2.IDKey accepts uint32 for the key length; the parser caps
	// the hash bytes at the maximum the encoder can emit (a few hundred
	// bytes), so the conversion below is safe in practice. The bound
	// check is defensive: a malformed encoding could in theory carry a
	// pathological length.
	if keyLen <= 0 || keyLen > maxArgon2idKeyLength {
		return ErrCredentialsInvalid
	}
	candidate := argon2.IDKey([]byte(presented), parsed.salt, parsed.iterations, parsed.memory, parsed.parallelism, uint32(keyLen))
	if subtle.ConstantTimeCompare(candidate, parsed.hash) != 1 {
		return ErrCredentialsInvalid
	}
	return nil
}

// maxArgon2idKeyLength is a defensive cap on the derived-key length the
// verifier accepts. A legitimate encoding emitted by [Argon2id.Hash]
// stays well under this; a malformed stored value claiming a giant key
// is rejected before invoking [argon2.IDKey].
const maxArgon2idKeyLength = 1024

// argon2idHash is the parsed view of a stored Argon2id encoding.
type argon2idHash struct {
	memory      uint32
	iterations  uint32
	parallelism uint8
	salt        []byte
	hash        []byte
}

// parseArgon2idEncoding parses the modular crypt format produced by
// [Argon2id.Hash]. It returns [ErrCredentialsInvalid] on any structural
// issue so the verifier never leaks why a comparison failed.
func parseArgon2idEncoding(s string) (argon2idHash, error) {
	parts := strings.Split(s, "$")
	if len(parts) != 6 || parts[0] != "" || parts[1] != "argon2id" {
		return argon2idHash{}, ErrCredentialsInvalid
	}
	if !strings.HasPrefix(parts[2], "v=") {
		return argon2idHash{}, ErrCredentialsInvalid
	}
	version, err := strconv.Atoi(parts[2][2:])
	if err != nil || version != argon2.Version {
		return argon2idHash{}, ErrCredentialsInvalid
	}
	mem, iter, par, err := parseArgon2idParams(parts[3])
	if err != nil {
		return argon2idHash{}, err
	}
	salt, err := base64.RawStdEncoding.DecodeString(parts[4])
	if err != nil {
		return argon2idHash{}, ErrCredentialsInvalid
	}
	hash, err := base64.RawStdEncoding.DecodeString(parts[5])
	if err != nil {
		return argon2idHash{}, ErrCredentialsInvalid
	}
	return argon2idHash{
		memory:      mem,
		iterations:  iter,
		parallelism: par,
		salt:        salt,
		hash:        hash,
	}, nil
}

// parseArgon2idParams extracts the m/t/p triple from the parameter
// segment ("m=...,t=...,p=...") of an Argon2id modular crypt encoding.
// Errors collapse onto [ErrCredentialsInvalid] so the caller cannot tell
// which sub-field tripped the parse.
func parseArgon2idParams(seg string) (mem, iter uint32, par uint8, err error) {
	for _, kv := range strings.Split(seg, ",") {
		k, v, ok := strings.Cut(kv, "=")
		if !ok {
			return 0, 0, 0, ErrCredentialsInvalid
		}
		n, parseErr := strconv.ParseUint(v, 10, 32)
		if parseErr != nil {
			return 0, 0, 0, ErrCredentialsInvalid
		}
		switch k {
		case "m":
			mem = uint32(n)
		case "t":
			iter = uint32(n)
		case "p":
			if n > 255 {
				return 0, 0, 0, ErrCredentialsInvalid
			}
			par = uint8(n)
		default:
			return 0, 0, 0, ErrCredentialsInvalid
		}
	}
	if mem == 0 || iter == 0 || par == 0 {
		return 0, 0, 0, ErrCredentialsInvalid
	}
	return mem, iter, par, nil
}

// ensure compile-time interface satisfaction.
var _ SecretVerifier = (*Argon2id)(nil)

// dummyVerify is a constant-time no-op used by [VerifyClient] when the
// caller targets a confidential method but the registered client has no
// stored hash. Without this the verifier would short-circuit before the
// hash work, leaking the existence of the client through timing.
//
// The function is unexported because it is only useful in conjunction
// with [VerifyClient].
func dummyVerify(presented string) {
	// Use the same Argon2id parameter set the verifier would use, so
	// the timing of the dummy path approximates the real one.
	p := Argon2idDefaults()
	_ = argon2.IDKey([]byte(presented), make([]byte, p.SaltLength),
		p.Iterations, p.Memory, p.Parallelism, p.KeyLength)
}
