package main

import (
	"fmt"
	"strings"
)

// header is the preamble of the generated report. It exists so a reader
// who lands on api/gates.md knows the file is an output, and knows what
// question the table answers.
const header = `# Gate topology

<!-- Generated by tools/gatetool from test/gates/gates.yaml. Do not edit by hand; run ` + "`make gates-write`" + `. -->

Every verification command this repository runs, the question it actually
answers, and the shipped surfaces it drives.

A gate reports on what it drives and nothing else. Reading a green gate as
a broader claim than the ` + "`Answers`" + ` column makes is the specific mistake
this table exists to prevent: the conformance suite has been green while a
defect lived in three shipped sign-in paths it never routes through.

**Levels.** ` + "`static`" + ` reads or compiles a surface without executing it.
` + "`unit`" + ` runs it in-process. ` + "`integration`" + ` drives it as a deployed
artifact — a booted example, a real browser, a real storage backend, or the
external conformance suite. A surface reached only at ` + "`static`" + ` level is
one nothing ever runs.
`

// Render produces the full generated report for m.
func Render(m *Map) string {
	var b strings.Builder
	b.WriteString(header)
	renderGates(&b, m)
	renderBlindSpots(&b, m)
	renderCoverage(&b, m)
	renderExemptions(&b, m)
	return b.String()
}

// renderGates writes the inventory table.
func renderGates(b *strings.Builder, m *Map) {
	b.WriteString("\n## Gates\n\n")
	b.WriteString("| Gate | Make target | In `make verify` | Level | Answers |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, g := range m.Gates {
		target := "—"
		if g.Target != "" {
			target = "`make " + g.Target + "`"
		}
		inVerify := "no"
		if g.InVerify {
			inVerify = "yes"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s |\n", g.ID, target, inVerify, g.Level, g.Answers)
	}
}

// renderBlindSpots writes what each gate cannot see. It is a section of
// its own because it is the part a reader consults when deciding what a
// green run entitles them to claim.
func renderBlindSpots(b *strings.Builder, m *Map) {
	b.WriteString("\n## What each gate cannot see\n\n")
	b.WriteString("A green result from the gate on the left says nothing about the classes on the right.\n\n")
	for _, g := range m.Gates {
		fmt.Fprintf(b, "**`%s`**\n\n", g.ID)
		for _, blind := range g.BlindTo {
			fmt.Fprintf(b, "- %s\n", blind)
		}
		b.WriteString("\n")
	}
}

// renderCoverage writes the surface matrix.
func renderCoverage(b *strings.Builder, m *Map) {
	b.WriteString("## Surface coverage\n\n")
	b.WriteString("| Surface | Deepest level | Driven by |\n")
	b.WriteString("|---|---|---|\n")
	for _, c := range m.Coverage() {
		deepest := string(c.Deepest())
		if deepest == "" {
			deepest = "**none**"
		}
		ids := make([]string, 0, len(c.Gates))
		for _, g := range c.Gates {
			ids = append(ids, "`"+g.ID+"`")
		}
		driven := "—"
		if len(ids) > 0 {
			driven = strings.Join(ids, ", ")
		}
		fmt.Fprintf(b, "| %s | %s | %s |\n", c.Surface.Title, deepest, driven)
	}
}

// renderExemptions writes the surfaces nothing runs, when there are any.
func renderExemptions(b *strings.Builder, m *Map) {
	var exempt []Coverage
	for _, c := range m.Coverage() {
		if c.Surface.StaticOnlyReason != "" {
			exempt = append(exempt, c)
		}
	}
	if len(exempt) == 0 {
		return
	}
	b.WriteString("\n## Surfaces nothing runs\n\n")
	b.WriteString("Each row is a deliberate decision, not an oversight. " +
		"A defect in one of these surfaces reaches a user before it reaches a gate.\n\n")
	b.WriteString("| Surface | Why no gate runs it |\n")
	b.WriteString("|---|---|\n")
	for _, c := range exempt {
		fmt.Fprintf(b, "| %s | %s |\n", c.Surface.Title, c.Surface.StaticOnlyReason)
	}
}
