#!/usr/bin/env bash
# Verify dependency licenses against the project allowlist.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

cd "$REPO_ROOT"

LICENSES="$(tool go-licenses)"

# Disallowed: AGPL, GPL (any), SSPL, BUSL, Elastic, Commons Clause.
disallowed_re='AGPL|^GPL|GPL-2|GPL-3|SSPL|BUSL|Elastic|Commons-Clause'

log "go-licenses report ./..."
"$LICENSES" report ./... 2>/dev/null | tee /tmp/go-licenses.csv

if grep -E "$disallowed_re" /tmp/go-licenses.csv >/dev/null; then
  die "disallowed license detected (see above)"
fi

log "All dependencies pass license allowlist."

# Regenerate LICENSES/THIRD_PARTY.md from the same report so the
# committed index never drifts from go.mod. The project's own module
# is filtered out (the repo's LICENSE is the canonical source for
# its own terms); rows are sorted lexicographically for a stable
# diff. CI catches drift through `git diff --exit-code` on this
# file after `make licenses` runs.
INDEX="$REPO_ROOT/LICENSES/THIRD_PARTY.md"
mkdir -p "$REPO_ROOT/LICENSES"
{
  printf '# Third-Party Licenses\n\n'
  printf 'This file is generated by `scripts/licenses.sh` from `go-licenses report ./...`. '
  printf 'Do not edit by hand — run `make licenses` to regenerate.\n\n'
  printf 'The project itself is licensed under Apache-2.0 (see `LICENSE` and `NOTICE` at the repo root).\n\n'
  printf '## Go module dependencies\n\n'
  printf '| Module | License | Source |\n'
  printf '|---|---|---|\n'
  grep -v '^github\.com/libraz/go-oidc-provider,' /tmp/go-licenses.csv \
    | sort \
    | while IFS=, read -r mod link lic; do
        printf '| `%s` | %s | <%s> |\n' "$mod" "$lic" "$link"
      done
} > "$INDEX"
log "Wrote $INDEX"
