#!/usr/bin/env bash
# Verify dependency licenses against the project allowlist, and
# regenerate THIRD_PARTY.md across the host module and every
# storage-adapter sub-module.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
source "$SCRIPT_DIR/lib.sh"

cd "$REPO_ROOT"

# go-licenses is pinned here rather than in tools/go.mod: v1.6.0 depends on an
# older otiai10/copy API than golangci-lint requires, so the two cannot share a
# module. `go run <pkg>@<version>` builds it in its own module graph, sidestepping
# that conflict while keeping the version pinned. (go-licenses/v2 is unusable —
# it treats the Go 1.26 standard library as "non go modules" and aborts.)
GOLICENSES_VERSION="v1.6.0"
GO_LICENSES=(go run "github.com/google/go-licenses@${GOLICENSES_VERSION}")

# Disallowed: AGPL, GPL (any), SSPL, BUSL, Elastic, Commons Clause.
disallowed_re='AGPL|^GPL|GPL-2|GPL-3|SSPL|BUSL|Elastic|Commons-Clause'

MERGED=/tmp/go-licenses.csv
: > "$MERGED"

run_module() {
  local mod="$1"
  local tags="${2:-}"
  if [ -n "$tags" ]; then
    log "go-licenses csv ./... ($mod, tags=$tags)"
    ( cd "$mod" && GOFLAGS="-tags=$tags" "${GO_LICENSES[@]}" csv ./... 2>/dev/null ) >> "$MERGED"
  else
    log "go-licenses csv ./... ($mod)"
    ( cd "$mod" && "${GO_LICENSES[@]}" csv ./... 2>/dev/null ) >> "$MERGED"
  fi
}

# Host module is always inspected. Storage-adapter sub-modules are
# inspected when present so their driver dependencies (mysql, pgx,
# sqlite, go-redis) appear in the canonical THIRD_PARTY.md. Example
# sub-modules are deliberately skipped: they pull in the same drivers
# transitively through the adapters they import, so adding them would
# only duplicate rows and surface tooling-only deps that the user
# never imports.
run_module "$REPO_ROOT"
if [ -f "$REPO_ROOT/op/storeadapter/sql/go.mod" ]; then
  # The SQL adapter does not import any driver itself — embedders
  # pick the engine and pass an open *sql.DB. The drivers
  # (modernc.org/sqlite, mysql, pgx) are surfaced via a build-tagged
  # licenses_drivers.go file gated by `//go:build licenses`, which is
  # compiled only by this script so the driver licenses appear in the
  # canonical THIRD_PARTY index without polluting regular builds.
  run_module "$REPO_ROOT/op/storeadapter/sql" licenses
fi
if [ -f "$REPO_ROOT/op/storeadapter/redis/go.mod" ]; then
  run_module "$REPO_ROOT/op/storeadapter/redis"
fi

if grep -E "$disallowed_re" "$MERGED" >/dev/null; then
  die "disallowed license detected (see above)"
fi

log "All dependencies pass license allowlist."

# Regenerate THIRD_PARTY.md from the merged report so the committed
# index never drifts from go.mod across the public modules. Project's
# own module rows (host + every sub-module) are filtered out — the
# repo's LICENSE is the canonical source for its own terms. Rows are
# deduplicated and sorted lexicographically for a stable diff.
# CI catches drift through `git diff --exit-code` on this file after
# `make licenses` runs.
INDEX="$REPO_ROOT/THIRD_PARTY.md"
{
  printf '# Third-Party Licenses\n\n'
  printf 'This file is generated by `scripts/licenses.sh` from `go-licenses csv ./...` runs '
  printf 'across the host module and every storage-adapter sub-module '
  printf '(`op/storeadapter/sql`, `op/storeadapter/redis`). '
  printf 'Do not edit by hand — run `make licenses` to regenerate.\n\n'
  printf 'The project itself is licensed under Apache-2.0 (see `LICENSE` and `NOTICE` at the repo root).\n\n'
  printf '## Go module dependencies\n\n'
  printf '| Module | License | Source |\n'
  printf '|---|---|---|\n'
  grep -v '^github\.com/libraz/go-oidc-provider' "$MERGED" \
    | sort -u \
    | while IFS=, read -r mod link lic; do
        printf '| `%s` | %s | <%s> |\n' "$mod" "$lic" "$link"
      done
} > "$INDEX"
log "Wrote $INDEX"
